language: cpp
sudo: required
dist: bionic
compiler:
- g++
os:
- linux
before_install:
- sudo apt-get update
- sudo apt-get install -y libpoco-dev
script:
- g++ -c -std=c++14 md5.cpp -o md5.o 
- g++ -std=c++14 md5.o -o md5 -lPocoFoundation

