dist: bionic
language: cpp

compiler:
  - gcc

install:
  - pip install conan

  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.17/cmake-3.17.1-Linux-x86_64.tar.gz
  - cat cmake-3.17.1-Linux-x86_64.tar.gz|md5sum
  - sha256sum -c ${TRAVIS_BUILD_DIR}/test/cmake_sha256.txt

  - tar -xvf cmake-3.17.1-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.17.1-Linux-x86_64 cmake-install
    
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .
  
  - ../test/test.sh
    
